// This file is auto-generated by the `update-kc-gen` command. Do not edit it manually.
// Hash: 52172bc691b7420440d04806699611c4695bca37485208382f0b36087da42efc

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

import { lazy, Suspense, type ReactNode } from "react"

export type ThemeName = "ol-learn" | "ol-data-platform"

export const themeNames: ThemeName[] = ["ol-learn", "ol-data-platform"]

export type KcEnvName = "POSTHOG_API_HOST" | "POSTHOG_API_KEY"

export const kcEnvNames: KcEnvName[] = ["POSTHOG_API_HOST", "POSTHOG_API_KEY"]

export const kcEnvDefaults: Record<KcEnvName, string> = {
  POSTHOG_API_HOST: "https://us.i.posthog.com",
  POSTHOG_API_KEY: ""
}

/**
 * NOTE: Do not import this type except maybe in your entrypoint.
 * If you need to import the KcContext import it either from src/login/KcContext.ts or src/account/KcContext.ts.
 * Depending on the theme type you are working on.
 */
export type KcContext =
  | import("./login/KcContext").KcContext
  | import("./account/KcContext").KcContext

declare global {
  interface Window {
    kcContext?: KcContext
  }
}

export const KcLoginPage = lazy(() => import("./login/KcPage"))
export const KcAccountPage = lazy(() => import("./account/KcPage"))

export function KcPage(props: { kcContext: KcContext; fallback?: ReactNode }) {
  const { kcContext, fallback } = props
  return (
    <Suspense fallback={fallback}>
      {(() => {
        switch (kcContext.themeType) {
          case "login":
            return <KcLoginPage kcContext={kcContext} />
          case "account":
            return <KcAccountPage kcContext={kcContext} />
        }
      })()}
    </Suspense>
  )
}

// NOTE: This is exported here only because in Webpack environnement it works differently
export const BASE_URL = import.meta.env.BASE_URL

// NOTE: This is only exported here because you're supposed to import type from different packages
// Depending of if you are using Vite, Webpack, ect...
export type { Meta, StoryObj } from "@storybook/react-vite"
